# Generated by Django 4.2.5 on 2023-09-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_lunch_account'),
        ('users', '0003_remove_profile_neco'),
    ]

    operations = [
    ]
