# Generated by Django 4.2.5 on 2023-09-12 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LunchMeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(default='meals/default.png', upload_to='meals')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LunchMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LunchMenuOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available_portions', models.IntegerField()),
                ('meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.lunchmeal')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.lunchmenu')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaDayDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_date', models.DateField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('registration_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction', models.CharField(max_length=200)),
                ('related_user', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_time', models.CharField(blank=True, choices=[('10:00', '10:00'), ('10:45', '10:45'), ('12:00', '12:00'), ('17:45', '17:45'), ('18:30', '18:30')], max_length=5, null=True)),
                ('selection', models.CharField(blank=True, choices=[('hawai', 'hawai'), ('funghi', 'funghi'), ('salami', 'salami'), ('ham & chicken', 'ham & chicken'), ('quattro formaggi', 'quattro formaggi'), ('deviola', 'deviola'), ('olives', 'olives'), ("doesn't matter which pizza", "doesn't matter which pizza")], max_length=26, null=True)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.profile')),
                ('pizza_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='food.pizzadayday')),
            ],
        ),
        migrations.CreateModel(
            name='LunchOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('menu_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.lunchmenuoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalLunchMenuOption',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('available_portions', models.IntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='food.lunchmeal')),
                ('menu', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='food.lunchmenu')),
            ],
            options={
                'verbose_name': 'historical lunch menu option',
                'verbose_name_plural': 'historical lunch menu options',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
